language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-23
    - ANDROID_ABI=armeabi-v7a

android:
  components:
  - tools
  - platform-tools
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
script:
  - ./gradlew build assembleAndroidTest
    
android:
  components:
    # Use the latest revision of Android SDK Tools
    - platform-tools
    - tools
    
    
    # The BuildTools version used by the project
    - build-tools-23.0.1

    # The SDK version used to compile the project
    - android-23

    # Repositories for Gradle and Maven
    - extra-android-m2repository
    - extra-google-m2repository
     - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

before_install:
 - chmod +x gradlew

android {
      lintOptions {
          abortOnError false
      }
  }
 
script:
  - ./gradlew clean build

